### ISSUE TITLE
[Question] Does it Make Sense to Use Hotmem for Vector/Matrix Abstract

### ISSUE THREAD

**Issue by zicklag** [eliasku/hotmem#1]
Hi, this library looks really cool, but I was wondering if you could help explain whether or not it would be useful for a particular use-case of mine. I am an experience programmer, but I have never dealt with lower-level code for memory management ( most of my experience is in Python and Haxe ).

I am interested in whether or not this library could help optimize [Armory3D](https://armory3d.org/) which is built on [Kha](https://github.com/kode/Kha). The specific instance I was wondering about was whether or not it makes sense to store vectors and matrices in a `hotmem.F32Array`. I was re-writing the Armory [Vec4](https://github.com/armory3d/iron/blob/master/Sources/iron/math/Vec4.hx) class to be an an Abstract that was backed by an `F32Array`, but while it appeared to work at first it was actually slower and would completely freeze up in a benchmark with 500,000 iterations of creating two vectors and doing some math with them.

This is probably because I don't understand how you are supposed to use the library, or in what instances that hotmem will actually help make stuff faster. If you could give me some guidance on how to use hotmem and how to help performance with it that would be great.

I put my in-progress vector class and my benchmark script in a [gist](https://gist.github.com/zicklag/8b1bc845bd29678a73814ce75532414d) so you can see them.

**Comment by eliasku** [comment]
Hello,
First of all, currently I have no plans to support ecx/hotmem/hxmake libraries in my spare time, as these libraries are experimental/educational projects.

I have experience to speed-up `poly2tri` library ~10x on HashLink and JavaScript without any additional memory management, just with simple and unsafe typed-arrays abstraction.

Feel free to use the example for your purposes:
```
package eks.polykit.poly2tri;

import eks.memory.F32s;
import eks.memory.U16s;

@:forward
abstract PointArray(U16s) from U16s {

	inline public function new(length:Int) {
		this = new U16s(length);
	}

	@:arrayAccess
	inline function getElement(index:Int):Point return (this[index]:Point);

	@:arrayAccess
	inline function setElement(index:Int, value:Point) this[index] = value;

	inline public function resize(newlen:Int):PointArray {
		return this.copyResize(newlen);
	}
}

abstract Point(Int) to Int from Int {

	static var POINTER:Int = 0;
	static var X:F32s;
	static var Y:F32s;
	static var EDGE:U16s;

	public static function initPool(max:Int) {
		POINTER = 0;
		if (X == null) X = new F32s(max);
		if (Y == null) Y = new F32s(max);
		if (EDGE == null) EDGE = new U16s(max);
	}

	public static function resizePool(max:Int) {
		X = X.copyResize(max);
		Y = Y.copyResize(max);
		EDGE = EDGE.copyResize(max);

		trace("RESIZE to " + max);
	}

	public function new(x:Float, y:Float) {
		this = POINTER++;
		if (this == X.length) {
			resizePool(this << 1);
		}
		X[this] = x;
		Y[this] = y;
		EDGE[this] = 0;
	}

	public var x(get, set):Float;
	public var y(get, set):Float;

	/// The edges this point constitutes an upper ending point
	public var edge_list(get, set):Edge;

	inline function get_x():Float return X[this];

	inline function set_x(value:Float):Float {
		X[this] = value;
		return value;
	}

	inline function get_y():Float return Y[this];

	inline function set_y(value:Float):Float {
		Y[this] = value;
		return value;
	}

	inline function get_edge_list():Edge return EDGE[this];

	inline function set_edge_list(value:Edge):Edge {
		EDGE[this] = value;
		return value;
	}
}
```
Similar to this all Point/Triangle/Edge are the simple `Int` values. So access is just picking values from one big pooled arrays. This hack is applieble to poly2tri because you need only allocate Objects and process them. Then you can simply reset all Pools and you don't need alloc/dealloc management.

On other hand, alloc individual `F32[4]` array for each `Vec4` is a bad idea for managed runtime. Access could be much slower, JIT will not recognize simple access and will not apply regular optimizations to general functions. Even with `hotmem` approach this is wrong way.

Data-oriented approach is more like in poly2tri example, where you need to process data. (I involve haxe abstract on top of arrays only to keep original codebase similar). So if you know input data structure, and output data structure you able to make right layout and optimize access and processing. `hotmem` just unsafe abstraction to help you manage big ranges of data.

The Math code is very generic. SIMD is the best technique to general math optimizations.

**Comment by zicklag** [comment]
Thanks a lot for spending the time to give me an answer! That info will help. :smiley:
